lab/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

urlpatterns = [
    path('', views.LandingPageView.as_view(), name='landing_page'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('settings/forgot-password/', views.ForgotPasswordView.as_view(), name='forgot_password'),
    path('404/', views.Test404View.as_view(), name='test_404'),
    path('500/', views.Test500View.as_view(), name='test_500'),
    path('dashboard/', views.DashboardView.as_view(), name='dashboard'),
    path('order_inbox/delete/', views.DeleteInboxView.as_view(), name='inbox_delete'),
    path('order_inbox/<str:order_code>/delete/', views.DeleteInboxOrderView.as_view(), name='inbox_order_delete'),
    path('settings/', views.SettingsView.as_view(), name='settings'),
    path('advanced_settings/', views.AdvancedSettingsView.as_view(), name='advanced_settings'),
    path('setup/', views.SetupView.as_view(), name='setup'),
    path('setup/laboratory_info/', views.LaboratoryUpdateView.as_view(), name='laboratory_update'),
    path('two_factor_auth', views.TwoFactorAuthView.as_view(), name='two_factor_auth'),
    path('two_factor_auth/setup', views.TwoFactorAuthSetupView.as_view(), name='two_factor_auth_setup'),

    # AWS debug
    path('aws_debug/', views.AWSDebugView.as_view(), name='aws_debug'),
    path('aws_debug/identifier/', views.AWSDebugIdentifierView.as_view(), name='aws_debug_identifiers'),

    # employees
    path('users/', views.UserListView.as_view(), name='user_list'),
    path('users/create/', views.UserCreateView.as_view(), name='user_create'),
    path('lab_admins/<str:lab_admin_uuid>/update/', views.LabAdminUpdateView.as_view(),
         name='lab_admin_update'),
    path('lab_admins/<str:lab_admin_uuid>/delete/', views.LabAdminDeleteView.as_view(),
         name='lab_admin_delete'),
    path('lab_collaborators/<str:lab_collaborator_uuid>/update/', views.LabCollaboratorUpdateView.as_view(),
         name='lab_collaborator_update'),
    path('lab_collaborators/<str:lab_collaborator_uuid>/delete/', views.LabCollaboratorDeleteView.as_view(),
         name='lab_collaborator_delete'),

    # providers
    path('provider/<str:provider_uuid>/signature/', views.ProviderSignatureUpdateView.as_view(), name='provider_signature'),
    path('provider/<str:provider_uuid>/delete_signature/', views.ProviderSignatureDeleteView.as_view(), name='provider_delete_signature'),

    # clia sample types
    path('clia_sample_types/<str:clia_sample_type_uuid>/', views.CLIASampleTypeDetailsView.as_view(),
         name='clia_sample_type_details'),

    # FDA Test List
    path('clia_test_types/', views.CLIATestTypeListView.as_view(), name='clia_test_type_list'),

    # billing
    path('billing/', views.BillingView.as_view(), name='billing'),

    # medication list
    path('medication_list/', views.MedicationListView.as_view(), name='medication_list'),

    # autocomplete views
    path('test_method_autocomplete/', views.TestMethodAutocomplete.as_view(), name='test_method_autocomplete'),
    path('test_target_autocomplete/', views.TestTargetAutocomplete.as_view(), name='test_target_autocomplete'),
    path('clia_test_type_autocomplete/', views.CliaTestTypeAutocomplete.as_view(), name='clia_test_type_autocomplete'),
    path('offsite_laboratory_autocomplete/', views.OffsiteLaboratoryAutocomplete.as_view(),
         name='offsite_laboratory_autocomplete'),
    path('instrument_autocomplete/', views.InstrumentAutocomplete.as_view(), name='instrument_autocomplete'),
    path('test_type_specialty_autocomplete/', views.TestTypeSpecialtyAutocomplete.as_view(),
         name='test_type_specialty_autocomplete'),
    path('payer_autocomplete/', views.PayerAutocomplete.as_view(),
         name='payer_autocomplete'),

    # initialize_data
    path('initialize_data/', views.InitializeDataView.as_view(), name='initialize_data'),

    # payer data
    path('payers/', views.PayerListView.as_view(), name='payer_list'),
    path('payers/create/', views.PayerCreateView.as_view(), name='payer_create'),
    path('payers/<str:payer_uuid>/', views.PayerDetailsView.as_view(), name='payer_details'),
    path('payers/<str:payer_uuid>/update/', views.PayerUpdateView.as_view(), name='payer_update'),
    path('payer/archived/', views.PayerArchivedListView.as_view(), name='payer_archived_list'),
    path('payers/<str:payer_uuid>/delete/', views.PayerDeleteView.as_view(), name='payer_delete'),
    path('payers/<str:payer_uuid>/undo_delete/', views.PayerUndoArchiveView.as_view(), name='payer_undo_delete'),

]

main/urls.py
from django.urls import include, path

from .tenant_admin import tenant_admin_site

urlpatterns = [
    path('', include('lab.urls')),
    path('', include('lab_tenant.urls')),
    path('', include('accounts.urls')),
    path('api/', include('main.api_urls')),
    path('codes/', include('codes.urls')),
    path('', include('orders.urls')),
    path('', include('patients.urls')),
    path('admin/', tenant_admin_site.urls),

]

accounts/models.py
import uuid as uuid_lib

from django.db import models
from django.utils import timezone
from django.contrib.postgres.fields import CICharField
from django.db.models.functions import Lower

from lab_tenant.models import User

from lab_tenant.models import AuditLogModel
from auditlog.registry import auditlog
from auditlog.models import AuditlogHistoryField
from main.storage_backends import PrivateMediaStorage


class Account(AuditLogModel):
    """
    Referring Providers
    """
    code = models.CharField(max_length=12, blank=True)
    uuid = models.UUIDField(
        db_index=True,
        default=uuid_lib.uuid4,
        editable=False
    )
    # IDs from different LISs
    alternate_id = models.CharField(max_length=32, blank=True)
    name = models.CharField(max_length=255, blank=True)
    user = models.OneToOneField(User, on_delete=models.SET_NULL, null=True)
    address1 = models.CharField(max_length=255, blank=True)
    address2 = models.CharField(max_length=255, blank=True)
    contact_person = models.CharField(max_length=255, blank=True)
    phone_number = models.CharField(max_length=255, blank=True)
    fax_number = models.CharField(max_length=255, blank=True)
    email = models.EmailField(null=True, blank=True)
    report_preference = models.CharField(max_length=20,
                                         choices=(('Final Reporting Only', 'Final Reporting Only'),
                                                  ('Partial Reporting', 'Partial Reporting')),
                                         default='Partial Reporting',
                                         blank=True)
    excluded_test_panels = models.ManyToManyField('orders.TestPanelType', related_name='excluded_accounts')
    # toggle send hl7 message
    results_out = models.BooleanField(default=False)
    results_out_include_base64_pdf = models.BooleanField(default=True)
    results_out_allow_partial = models.BooleanField(default=False)
    # Link of PDF in HL7 Message (default FALSE)
    results_out_show_pdf_link = models.BooleanField(default=False)
    requisition_form = models.FileField(storage=PrivateMediaStorage(), null=True)
    zip_code = models.CharField(max_length=128, blank=True)
    account_manages_signatures = models.BooleanField(default=False)
    emr_account_number = models.CharField(max_length=255, blank=True)
    notes = models.TextField(blank=True)

    class Meta:
        db_table = 'account'
        ordering = [Lower('name')]

    def __str__(self):
        if self.address1:
            return "{}".format(self.name)
        else:
            return self.name


class AccountAlias(AuditLogModel):
    account = models.ForeignKey('Account', related_name='account_aliases',
                                on_delete=models.SET_NULL, null=True)
    name = CICharField(max_length=255, blank=True)

    def __str__(self):
        return self.name


class Provider(AuditLogModel):
    """

    """
    uuid = models.UUIDField(
        db_index=True,
        default=uuid_lib.uuid4,
        editable=False
    )
    # IDs from different LISs
    alternate_id = models.CharField(max_length=32, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    # providers can be part of multiple Accounts
    accounts = models.ManyToManyField(Account, related_name='providers')
    # Jr, II, etc.
    suffix = models.CharField(max_length=255, blank=True)
    # MD, RN, CNA, etc.
    title = models.CharField(max_length=255, blank=True)
    # national physician identifier
    npi = models.CharField(max_length=10, blank=True)
    # other identifier (for non US providers)
    id_num = models.CharField(max_length=255, blank=True)
    phone_number = models.CharField(max_length=255, blank=True)
    fax_number = models.CharField(max_length=255, blank=True)
    signature = models.FileField(storage=PrivateMediaStorage(), null=True)

    class Meta:
        db_table = 'provider'
        ordering = [Lower('user__last_name')]

    def __str__(self):
        if self.npi:
            return "{} {}, {} - {}".format(self.user.first_name, self.user.last_name, self.title, self.npi)
        else:
            return "{}, {}".format(self.user.last_name, self.user.first_name)


class Collector(AuditLogModel):
    """
    """
    uuid = models.UUIDField(
        db_index=True,
        default=uuid_lib.uuid4,
        editable=False
    )
    # IDs from different LISs
    alternate_id = models.CharField(max_length=32, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, related_name='collector')
    # providers can be part of multiple Accounts
    accounts = models.ManyToManyField(Account, related_name='collectors')

    class Meta:
        ordering = [Lower('user__last_name')]


class CriticalContact(AuditLogModel):
    account = models.ForeignKey('Account', null=True, on_delete=models.SET_NULL, related_name='critical_contacts')
    alternate_id = models.CharField(max_length=32, blank=True)
    last_name = models.CharField(max_length=255, blank=True)
    first_name = models.CharField(max_length=255, blank=True)
    phone_number = models.CharField(max_length=255, blank=True)
    fax_number = models.CharField(max_length=255, blank=True)
    email = models.EmailField(null=True, blank=True)

    def __str__(self):
        return '{}, {}'.format(self.last_name, self.first_name)



######################################################################################################################
# Django AuditLogs

auditlog.register(Account)
auditlog.register(Provider)
auditlog.register(Collector)
auditlog.register(CriticalContact)

lab/templates/account_create.html
{% extends "base.html" %}
{% load static %}

{% block css %}
  <style>
    .required_label:after {
     content:"*";
     color:red;
  }
  </style>
{% endblock %}

{% block content %}
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
    {% if update %}
      <h2>Update {{ object_name.0 }}</h2>
    {% else %}
      <h2>Create {{ object_name.0 }}</h2>
    {% endif %}

    <div class="btn-toolbar mb-2 mb-md-2">
      <div class="btn-group mr-2">
        <a href="{% url 'account_list' %}" class="btn btn-sm btn-secondary"><i class="fas fa-angle-left"></i>&nbsp;&nbsp;Back</a>
      </div>
    </div>
  </div>

  {% if form.errors %}
    {% for field in form %}
      {% for error in field.errors %}
        <div class="alert alert-danger">
          <strong>{{ error|safe }}</strong>
        </div>
      {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
      <div class="alert alert-danger">
        <strong>{{ error|safe }}</strong>
      </div>
    {% endfor %}
  {% endif %}

  <div class="row">
    <div class="col-12">

      <div class="card">
        <div class="card-body">

          <form method="POST">
            {% csrf_token %}

              <label>{{ form.providers.label }}</label>
              {{ form.providers }} &nbsp;&nbsp;
              <i class="fas fa-info-circle" data-toggle="tooltip"
                 title="Providers must be created in the system first (see the sidebar under Groups)
                 before they can be added to an account or location.">
              </i>
              <br><br>

              <label class="required_label">{{ form.account_name.label }}</label>
              <input name="{{ form.account_name.name }}"
                     value="{{ form.account_name.value|default_if_none:'' }}"
                     class="form-control"><br>

              <label>{{ form.alternate_id.label }}</label>
              <input name="{{ form.alternate_id.name }}"
                     value="{{ form.alternate_id.value|default_if_none:'' }}"
                     class="form-control"><br>

              <div class="form-row">
                  <div class="col-4">
                    <label>{{ form.aliases.label }}</label>
                    {{ form.aliases }}
                  </div>
              </div><br>

              <div class="form-row">
                <div class="col-6">
                  <label class="required_label">{{ form.account_address1.label }}</label>
                  <input id="address1" name="{{ form.account_address1.name }}"
                         value="{{ form.account_address1.value|default_if_none:'' }}"
                         class="form-control">
                </div>
                <div class="col-3">
                  <label>{{ form.account_address2.label }}</label>
                  <input name="{{ form.account_address2.name }}"
                         value="{{ form.account_address2.value|default_if_none:'' }}"
                         class="form-control">
                </div>
                <div class="col-3">
                  <label>{{ form.account_zip_code.label }}</label>
                  <input name="{{ form.account_zip_code.name }}"
                         value="{{ form.account_zip_code.value|default_if_none:'' }}"
                         class="form-control" id="zip-code">
                </div>
              </div><br>

              <div class="form-row">
                <div class="col-6">
                  <label>{{ form.contact_person.label }}</label>
                  <input name="{{ form.contact_person.name }}"
                         value="{{ form.contact_person.value|default_if_none:'' }}"
                         class="form-control">
                </div>
                <div class="col-6">
                  <label>{{ form.account_phone.label }}</label>
                  <input name="{{ form.account_phone.name }}"
                         value="{{ form.account_phone.value|default_if_none:'' }}"
                         class="form-control phoneNumberMask">
                </div>
              </div><br>

              <div class="form-row">
                <div class="col-6">
                  <label>{{ form.account_fax.label }}</label>
                  <input name="{{ form.account_fax.name }}"
                         value="{{ form.account_fax.value|default_if_none:'' }}"
                         class="form-control phoneNumberMask">
                </div>
                <div class="col-6">
                  <label>{{ form.account_email.label }}</label>
                  {{ form.account_email }}
                </div>

              </div><br>

              <div class="form-row">
                <div class="col-4">
                  <label>{{ form.report_preference.label }}</label>
                  {{ form.report_preference }}
                </div>
              </div><br>

              <div class="form-row">
                <div class="col-4">
                  <label>{{ form.emr_account_number.label }}</label>
                  {{ form.emr_account_number }}
                </div>
              </div><br>

              <div class="form-row">
                <div class="col-4">
                  <label>{{ form.notes.label }}</label>
                  {{ form.notes }}
                </div>
              </div><br>

              <div class="form-row">
                <div class="col-4">
                  <label>
                    {{ form.results_out_show_pdf_link }}
                    {{ form.results_out_show_pdf_link.label }}
                  </label>
                </div>
              </div>

              <div class="form-row">
                <div class="col-4">
                  <label>
                      {{ form.account_manages_signatures }}
                      {{ form.account_manages_signatures.label }}
                  </label>
                </div>
              </div>
            <hr>

            <div class="form-row">
              <div class="col-6">
                <label>{{ form.account_username.label }}</label>
                {{ form.account_username }}
              </div>
            </div>
            <br>
            <div class="form-row">
              <div class="col-6">
                <label>{{ form.account_password.label }}</label>
                {{ form.account_password }}
              </div>
            </div>
            <div class="form-row">
              <div class="col-6">
                <label>{{ form.account_password_confirm.label }}</label>
                {{ form.account_password_confirm }}
              </div>
            </div>
          <hr>


            {% if update %}
              <button type="submit" class="btn btn-primary">Update {{ object_name.0 }}</button>
            {% else %}
              <button type="submit" class="btn btn-primary">Create {{ object_name.0 }}</button>
            {% endif %}

          </form>

        </div>

      </div>
    </div>

  </div>




{% endblock %}


{% block javascript %}
	<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD1CC8IDTw8qL6U-zeXgxcP9uOe6cbFqhs&sensor=false&libraries=places&language=en"></script>
	<script src="{% static 'lib/inputmask/min/jquery.inputmask.bundle.min.js' %}"></script>
  <script src="{% static 'js/zip_code_autofill.js' %}"></script>
  <!-- Custom JS -->
	<script>

		// Google Maps Autocomplete
		let address1 = document.getElementById('address1');
		// restrict to only addresses
    let autocomplete1 = new google.maps.places.Autocomplete(address1, {types:['address']});
    autofill_zip_code(autocomplete1, 'zip-code');

		// phone number mask for HTML
		$('.phoneNumberMask').inputmask({"mask": "(999) 999-9999"}); //specifying options

	</script>
{% endblock %}

{% block footer  %}
  <!-- required for Django autocomplete light -->
  {{ form.media }}
{% endblock %}

lab/templates/account_details.html
{% extends "base.html" %}
{% load static %}
{% load timezone %}

{% block css %}

  <style>
    .provider-table {
      height: 300px;
      overflow:auto;
    }
  </style>
{% endblock %}

{% block content %}
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
    <h2>{{ account.name }}</h2>

    <div class="btn-toolbar mb-2 mb-md-0">
      <div class="btn-group mr-2">
        {% if account.requisition_form %}
          <a href="{{ account.requisition_form.url }}" class="btn btn-sm btn-primary mr-2" target="_blank"><i class="fas fa-search"></i>&nbsp;&nbsp;Account Requisition Form</a>
        {% endif %}
        <!-- Delete button -->
        <a href="#" class="btn btn-sm btn-danger" onclick="deleteObj()"><i class="far fa-trash-alt"></i>&nbsp;&nbsp;{{ object_name.0 }}</a>
        <!-- /Delete button -->
        <a href="{% url 'account_update' account.uuid %}" class="btn btn-sm btn-warning ml-2"><i class="fas fa-pencil-alt"></i>&nbsp;&nbsp;{{ object_name.0 }}</a>
        <a href="#" onClick="javascript:history.go(-1)" class="btn btn-sm btn-secondary ml-2"><i class="fas fa-angle-left"></i>&nbsp;&nbsp;Back</a>
      </div>
    </div>
  </div>

  {% if messages %}
    {% for message in messages %}
      {% if message.tags == 'success' %}
        <div class="alert alert-success">
          <strong>{{ message|escape }}</strong>
        </div>
      {% elif message.tags == 'error' %}
        <div class="alert alert-danger">
          <strong>{{ message|escape }}</strong>
        </div>
      {% else %}
        <div class="alert alert-info">
          <strong>{{ message|escape }}</strong>
        </div>
      {% endif %}
    {% endfor %}
  {% endif %}

  <div class="row">

    <div class="col-6">
      <div class="card h-100">
        <div class="card-body">
          {% if account.alternate_id %}
            <p><b>ID</b><br> {{ account.id|default:'-' }} ({{ account.alternate_id }})</p>
          {% else %}
            <p><b>ID</b><br> {{ account.id|default:'-' }}</p>
          {% endif %}
          <p><b>Aliases</b><br>
            {% for alias in account.account_aliases.all %}
              {{ alias }}<br>
            {% endfor %}
          </p>
          <p><b>Date added</b><br> {{ account.created_date|as_timezone:request.tenant.timezone }}</p>
          <p><b>Address</b><br> {{ account.address1|default:'-' }}<br>{% if account.address2 %}
            {{ account.address2 }}{% endif %}{% if account.zip_code or account.zip_code.strip != '' %}{% if account.address2 %}, {% endif %}
            {{ account.zip_code|default:'-' }}{% endif %}</p>
          <p><b>Contact</b><br> {{ account.contact_person|default:'-' }}</p>
          <p><b>Phone #</b><br> {{ account.phone_number|default:'-' }}</p>
          <p><b>Fax #</b><br> {{ account.fax_number|default:'-' }}</p>
          <p><b>Email</b><br> {{ account.email|default:'-' }}</p>
          {% if user.user_type < 9 %}
            <p><b>Username </b><br> {{ account.user.username|default:'-' }}</p>
          {% endif %}
          <p><b>Reporting Preference</b><br> {{ account.report_preference }}</p>
          <p><b>EMR Account Number</b><br> {{ account.emr_account_number|default:"-" }}</p>
          <p><b>Link of PDF in HL7 Message</b><br> {{ account.results_out_show_pdf_link }}</p>
          <p><b>Account Manages Signatures on File</b><br> {{ account.account_manages_signatures }}</p>
          <p><b>Internal Notes</b><br><i>{{ account.notes }}</i></p>
        </div>
      </div>
    </div>

    <div class="col-6">
      <div class="card h-100">
        <div class="card-body provider-table">
          <h5 class="card-title">Provider List</h5>
          <table class="table mb-0">
            <tr>
              <th>Last Name</th>
              <th>First Name</th>
              <th>NPI</th>
            </tr>
            {% for provider in provider_list %}
            <tr>
              <td><a href="{% url 'provider_details' provider_uuid=provider.uuid %}">{{ provider.user.last_name }}</a></td>
              <td><a href="#">{{ provider.user.first_name }}</a></td>
              <td>{{ provider.npi }}</td>
            </tr>
            {% endfor %}
          </table>
        </div>
      </div>
    </div>

  </div>

  <br><br>

  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-header">
          Critical Contacts
          <div class="btn-group mr-2 float-right">
              <a href="{% url 'critical_contact_create' account_uuid=account.uuid %}" class="btn btn-sm btn-primary ml-2">
                <i class="fas fa-plus"></i>&nbsp;&nbsp;Critical Contact
              </a>
          </div>
        </div>
        <div class="card-body">
          <div class="handsontable" id="critical-contact-table"></div>
        </div>
      </div>
    </div>
  </div>

  <!-- Reported Orders Table -->
  <div class="row">
    <div class="col-12">

      <div class="card">
        <div class="card-body">
          <h4>Reported Orders</h4>
          <div class="handsontable" id="account-reported-orders-table"></div>
        </div>
      </div>

    </div>
  </div>
  <!-- /Reported Orders Table -->

{% endblock %}


{% block javascript %}
  <!-- Custom JS -->
  <script type="text/javascript" src="{% static 'utils/custom_renderers.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/account_details.js' %}"></script>
	<script>
  let accountReportedOrdersTable;
    // account reported orders handsontable
    $.ajax({
      url: '/api/v1/internal/account_reported_orders_table/{{ account.uuid }}/',
      dataType: 'json',
      success: function (orders) {
        accountReportedOrdersTable = createAccountReportedOrdersTable(orders, accountReportedOrdersTable)
      },
      error: function () {
        console.log("account reported orders table api call failed")
      }
    });

  // delete the object only if confirmed
  function deleteObj() {
    let result = confirm("Are you sure you want to archive this {{ object_name.1 }}?");
    if (result) {
      // logic to delete the item
      // delete is performed using a GET request here
      window.location.replace("{% url 'account_delete' account_uuid=account.uuid %}");
    }
  }

  function createCriticalContactTable(data, table) {

      if (!table) {
        const hotElement = document.querySelector('#critical-contact-table');
        const hotSettings = {
          data: data,
          columns: [
            {
              data: 'last_name',
              editor: false,
              width: 10,
            },
            {
              data: 'first_name',
              editor: false,
              width: 200,
            },
            {
              data: 'phone_number',
              editor: false,
              type: 'text',
              width: 200,
            },
            {
              data: 'update_link',
              editor: false,
              renderer: 'html',
              className: 'htCenter',
              width: 5,
            },
            {
              data: 'delete_link',
              editor: false,
              renderer: 'html',
              className: 'htCenter',
              width: 5,
            },
          ],
          stretchH: 'all',
          //width: 806,
          height: 400,
          autoColumnSize: true,
          autoWrapRow: true,
          manualRowResize: false,
          manualColumnResize: false,
          columnSorting: true,
          sortIndicator: true,
          rowHeaders: false,
          colHeaders: true,
          nestedHeaders: [
            [
              'Last Name',
              'First Name',
              'Phone Number',
              'Update',
              'Archive',
            ],
          ],
          manualRowMove: false,
          manualColumnMove: false,
          contextMenu: false,
          filters: true,
          dropdownMenu: ['filter_by_condition', 'filter_action_bar'],
          afterGetColHeader: function(col, TH) {
            TH.className = 'center';
          },
        };

        return new Handsontable(hotElement, hotSettings);
      } else {
        // load new data without replacing old table
        table.getPlugin('filters').clearConditions();
        return table;
      }
    }

    let criticalContactTable;
      // recent order handsontable
      $.ajax({
        url: '/api/v1/internal/critical_contact_table/{{ account.uuid }}',
        dataType: 'json',
        success: function (data) {
          criticalContactTable = createCriticalContactTable(data, criticalContactTable)
        },
        error: function () {
          console.log("critical contacts table api call failed")
        }
      });

	</script>
{% endblock %}

lab/templates/batch_printed_reports.html
{#{% extends "base.html" %}#}
{#{% load static %}#}
{##}
{#{% block css %}#}
{#  <link rel="stylesheet" href="{% static 'lib/handsontable/handsontable_pro.min.css' %}" type="text/css" />#}
{#{% endblock %}#}
{##}
{#{% block content %}#}
{##}
{#  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">#}
{#    <h2>Dashboard</h2>#}
{#    <div class="btn-toolbar mb-2 mb-md-0">#}
{#      <div class="btn-group mr-2">#}
{#        <a href="{% url 'order_create' %}" class="btn btn-primary ml-2">#}
{#          <i class="fas fa-plus"></i>&nbsp;&nbsp;Order#}
{#        </a>#}
{#      </div>#}
{#    </div>#}
{#  </div><br>#}
{##}
{#  {% if messages %}#}
{#    {% for message in messages %}#}
{#      {% if message.tags == 'success' %}#}
{#        <div class="alert alert-success">#}
{#          <strong>{{ message|escape }}</strong>#}
{#        </div>#}
{#      {% elif message.tags == 'error' %}#}
{#        <div class="alert alert-danger">#}
{#          <strong>{{ message|escape }}</strong>#}
{#        </div>#}
{#      {% else %}#}
{#        <div class="alert alert-info">#}
{#          <strong>{{ message|escape }}</strong>#}
{#        </div>#}
{#      {% endif %}#}
{#    {% endfor %}#}
{#  {% endif %}#}
{##}
{#  {% if form.errors %}#}
{#    {% for field in form %}#}
{#      {% for error in field.errors %}#}
{#        <div class="alert alert-danger">#}
{#          <strong>{{ error|escape }}</strong>#}
{#        </div>#}
{#      {% endfor %}#}
{#    {% endfor %}#}
{#    {% for error in form.non_field_errors %}#}
{#      <div class="alert alert-danger">#}
{#        <strong>{{ error|escape }}</strong>#}
{#      </div>#}
{#    {% endfor %}#}
{#  {% endif %}#}
{##}
{#  <div class="row">#}
{#    <form action="ex_form" target="_blank">#}
{##}
{#   </form>#}
{#  </div>#}
{##}
{##}
{#{% endblock %}#}
{##}
{##}
{#{% block javascript %}#}
{#{% endblock %}#}

<embed src={% url 'pdf' %}'#toolbar=0&navpanes=0&scrollbar=0'style="width:718px; height:700px;" frameborder="0">